/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.JobProviderOrg.InterviewSchedulerRole;

import Business.CandidateProfile.CandidateProfile;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.JobDetails.JobDetails;
import Business.Organization.JobProviderOrganization.InterviewSchedulerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.InterviewSchedulerWorkRequest;
import Business.WorkQueue.JobPostingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.JobProviderOrg.ApplicationProcessRole.ApplicationProcessWorkAreaJPanel;
import userinterface.JobProviderOrg.JobPostingRole.PostedJobJPanel;

/**
 *
 * @author bhargavisabbisetty
 */
public class InterviewSchedulerWorkAreaJPanel extends javax.swing.JPanel {
 private JPanel userProcessContainer;
    private InterviewSchedulerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form InterviewSchedulerWorkAreaJPanel
     */
    public InterviewSchedulerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, InterviewSchedulerOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;

        populateWorkQueueTable();
    }
public void populateWorkQueueTable() {

        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();

        model.setRowCount(0);

        for (WorkRequest work : organization.getWorkQueue().getWorkRequestList()) {
            if (work instanceof InterviewSchedulerWorkRequest) {
                InterviewSchedulerWorkRequest interviewWorkRequest = (InterviewSchedulerWorkRequest) work;
                Object[] row = new Object[4];
                row[0] = interviewWorkRequest.getJobDetails();
                row[1] = interviewWorkRequest;
               
               
                row[2] = interviewWorkRequest.getCandidateReview();
 
                row[3] = interviewWorkRequest.getStatus();
                model.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        view_Candidate_Profile = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Superclarendon", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("WELCOME TO INTERVIEW SCHEDULER WORKAREA");

        requestTable.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Main skills", "Candidate's Review", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        viewBtn.setBackground(new java.awt.Color(0, 51, 255));
        viewBtn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("View Job Details");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        view_Candidate_Profile.setBackground(new java.awt.Color(0, 102, 102));
        view_Candidate_Profile.setFont(new java.awt.Font("Chalkboard SE", 0, 12)); // NOI18N
        view_Candidate_Profile.setForeground(new java.awt.Color(255, 255, 255));
        view_Candidate_Profile.setText("View Candidate Profile");
        view_Candidate_Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_Candidate_ProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(view_Candidate_Profile, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(viewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(view_Candidate_Profile)
                .addContainerGap(265, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = requestTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        InterviewSchedulerWorkRequest request = (InterviewSchedulerWorkRequest) requestTable.getValueAt(selectedRow, 1);
        JobDetails jobDetails = request.getJobDetails();
        
//        request.setStatus("Processing");
        Job_Details_JPanel job_details_jpanel = new Job_Details_JPanel(userProcessContainer,userAccount,organization, enterprise,business,jobDetails);
        userProcessContainer.add("PostedJobJPanel", job_details_jpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_viewBtnActionPerformed

    private void view_Candidate_ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_Candidate_ProfileActionPerformed
        // TODO add your handling code here:
         int selectedRow = requestTable.getSelectedRow();

        if (selectedRow < 0) {
            return;
        }

        InterviewSchedulerWorkRequest request = (InterviewSchedulerWorkRequest) requestTable.getValueAt(selectedRow, 1);
//        CandidateProfile candidateProfile = request.getCandidateprofile();
//        request.setStatus("Processing");
        View_Veteran_Info_JPanel view_details = new View_Veteran_Info_JPanel(userProcessContainer,userAccount,organization, enterprise,business,request);
        userProcessContainer.add("view details", view_details);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_view_Candidate_ProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestTable;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton view_Candidate_Profile;
    // End of variables declaration//GEN-END:variables
}
