/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EventManagementOrg.EventManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EventManagementOrganization.EventManagementOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhargavisabbisetty
 */
public class EventManagerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EventManagementOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    /**
     * Creates new form EventAttendeeManagerWorkAreaJPanel
     */
    public EventManagerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EventManagementOrganization organization, Enterprise enterprise,EcoSystem business) { 
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business = business;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CreateEventBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        CreateEventBtn.setBackground(new java.awt.Color(0, 51, 255));
        CreateEventBtn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        CreateEventBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateEventBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welvets_pictures/create2.png"))); // NOI18N
        CreateEventBtn.setText("Create");
        CreateEventBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateEventBtnActionPerformed(evt);
            }
        });

        ViewBtn.setBackground(new java.awt.Color(0, 51, 255));
        ViewBtn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        ViewBtn.setForeground(new java.awt.Color(255, 255, 255));
        ViewBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/welvets_pictures/view.gif"))); // NOI18N
        ViewBtn.setText("View");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CreateEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(CreateEventBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(ViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateEventBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateEventBtnActionPerformed
        // TODO add your handling code here:
        EventCreateWorkAreaJPanel ECJPanel = new EventCreateWorkAreaJPanel(userProcessContainer, userAccount, organization , enterprise, business);
        userProcessContainer.add("manageOrganizationJPanel", ECJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_CreateEventBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        EventViewWorkAreaJPanel EVJPanel = new EventViewWorkAreaJPanel(userProcessContainer, userAccount, organization , enterprise, business);
        userProcessContainer.add("manageOrganizationJPanel", EVJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateEventBtn;
    private javax.swing.JButton ViewBtn;
    // End of variables declaration//GEN-END:variables
}
