/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VeteranOrg.VeteranRole;

import Business.EcoSystem;
import Business.Enterprise.ConsultancyEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.ConsultancyOrganization.ConsultantOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ConsultancyServiceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bhargavisabbisetty
 */
public class Consultancy_Registration_Form_JPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount userAccount;
    EcoSystem business;
    /**
     * Creates new form Consultancy_Registration_Form_JPanel
     */
    public Consultancy_Registration_Form_JPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Job_Name_TB = new javax.swing.JTextField();
        min_Sal_CB = new javax.swing.JComboBox();
        max_Sal_CB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        Register_Btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();
        Job_Type_CB = new javax.swing.JComboBox();
        Location_CB = new javax.swing.JComboBox();

        jLabel7.setText("jLabel7");

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Superclarendon", 0, 18)); // NOI18N
        jLabel1.setText("Registration Form");

        jLabel2.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel2.setText("Location:");

        jLabel3.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel3.setText("Salary Range:");

        jLabel4.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel4.setText("Job Name:");

        jLabel5.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel5.setText("Job Type:");

        min_Sal_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5000", "10000", "15000", "20000", "25000", "30000", "35000", "40000" }));

        max_Sal_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10000", "15000", "20000", "25000", "30000", "35000", "40000", "45000" }));

        jLabel6.setText("to");

        Register_Btn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        Register_Btn.setForeground(new java.awt.Color(0, 51, 255));
        Register_Btn.setText("Register");
        Register_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register_BtnActionPerformed(evt);
            }
        });

        Back_Btn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(0, 51, 255));
        Back_Btn.setText("Back");
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });

        Job_Type_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "On-Site", "Remote Only" }));

        Location_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atlanta", "Austin", "Boston", "Charlotte", "Chicago", "Dallas", "Denver", "Detroit", "Houston", "Los Angeles", "Memphis", "New York", "Oklahoma  City", "Portland", "Raleigh", "San Antonio", "San Francisco", "San Jose", "Seattle", "Washington, D.C." }));
        Location_CB.setActionCommand("null");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Location_CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Job_Name_TB)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(min_Sal_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(max_Sal_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Job_Type_CB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(229, 229, 229))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Register_Btn)
                                .addGap(29, 29, 29)
                                .addComponent(Back_Btn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Location_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(min_Sal_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(max_Sal_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4))
                    .addComponent(Job_Name_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(Job_Type_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Register_Btn)
                    .addComponent(Back_Btn))
                .addContainerGap(82, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Register_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register_BtnActionPerformed
        // TODO add your handling code here:
        boolean Valid=true;
        Integer max = Integer.parseInt(max_Sal_CB.getSelectedItem().toString());
        Integer min = Integer.parseInt(min_Sal_CB.getSelectedItem().toString());
        if(min>=max){
            JOptionPane.showMessageDialog(null, "Minimum Salary cannot be greater than equal to Maximum Salary");
            Valid = false;
        }
        
        if(Valid){
        System.out.println("hi");
        ConsultancyServiceWorkRequest cswr = new ConsultancyServiceWorkRequest();
        cswr.setMax_Salary(Integer.parseInt(max_Sal_CB.getSelectedItem().toString()));
        cswr.setMin_Salary(Integer.parseInt(min_Sal_CB.getSelectedItem().toString()));
        cswr.setEnterprise(enterprise);
        cswr.setJobType(Job_Type_CB.getSelectedItem().toString());
        cswr.setLocation(Location_CB.getSelectedItem().toString());
        cswr.setJobName(Job_Name_TB.getText());
        cswr.setUser(userAccount);
        cswr.setSender(userAccount);
        cswr.setStatus("Registered");
        System.out.println(cswr);
        Organization org = null;
//        for (Network network : business.getNetworkList()) {
//            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//                        if (enterprise instanceof ConsultancyEnterprise) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization instanceof ConsultantOrganization) {
                                    org = organization;
                                    System.out.println(org.getName());
                                    break;
                                }
                            }
                        
                    
                
                if (org != null) {
                    System.out.println("inside");
                    org.getWorkQueue().getWorkRequestList().add(cswr);
                    userAccount.getWorkQueue().getWorkRequestList().add(cswr);
//                    userAccount.getWorkQueue().getWorkRequestList().add(jr);
                    JOptionPane.showMessageDialog(null, "Your Application is successfully submitted");
                    System.out.println("successfully submitted");
                }
            

        }
        
    }//GEN-LAST:event_Register_BtnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        New_Consultancy_job_JPanel consultancy_jpanel = (New_Consultancy_job_JPanel) component;
        consultancy_jpanel.populateNetwork();
//        System.out.println(request.getStatus());
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_Back_BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JTextField Job_Name_TB;
    private javax.swing.JComboBox Job_Type_CB;
    private javax.swing.JComboBox Location_CB;
    private javax.swing.JButton Register_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox max_Sal_CB;
    private javax.swing.JComboBox min_Sal_CB;
    // End of variables declaration//GEN-END:variables
}
