/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VeteranOrg.VeteranRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhargavisabbisetty
 */
public class Consultancy_Menu_JPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
    /**
     * Creates new form Consultancies_Menu_JPanel
     */
    public Consultancy_Menu_JPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        New_Consultancies = new javax.swing.JButton();
        Registered_Consultancies_Btn = new javax.swing.JButton();
        Back_Btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        New_Consultancies.setBackground(new java.awt.Color(0, 51, 255));
        New_Consultancies.setFont(new java.awt.Font("Superclarendon", 1, 13)); // NOI18N
        New_Consultancies.setForeground(new java.awt.Color(255, 255, 255));
        New_Consultancies.setText("New Consultancies");
        New_Consultancies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_ConsultanciesActionPerformed(evt);
            }
        });

        Registered_Consultancies_Btn.setBackground(new java.awt.Color(0, 51, 255));
        Registered_Consultancies_Btn.setFont(new java.awt.Font("Superclarendon", 1, 13)); // NOI18N
        Registered_Consultancies_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Registered_Consultancies_Btn.setText("Registered Consultancies");
        Registered_Consultancies_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Registered_Consultancies_BtnActionPerformed(evt);
            }
        });

        Back_Btn.setBackground(new java.awt.Color(0, 51, 255));
        Back_Btn.setFont(new java.awt.Font("Superclarendon", 1, 13)); // NOI18N
        Back_Btn.setForeground(new java.awt.Color(255, 255, 255));
        Back_Btn.setText("Back");
        Back_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(New_Consultancies, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Registered_Consultancies_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Back_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(New_Consultancies, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registered_Consultancies_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Back_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void New_ConsultanciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_ConsultanciesActionPerformed
        // TODO add your handling code here:
        New_Consultancy_job_JPanel new_consultancy_job= new New_Consultancy_job_JPanel(userProcessContainer, userAccount,  enterprise, business);
        userProcessContainer.add("List of consultancies JPanel", new_consultancy_job);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_New_ConsultanciesActionPerformed

    private void Registered_Consultancies_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Registered_Consultancies_BtnActionPerformed
        // TODO add your handling code here:
        Registered_Consultancy_job_JPanel reg_consultancy_job= new Registered_Consultancy_job_JPanel(userProcessContainer, userAccount,  enterprise, business);
        userProcessContainer.add("Registered consultancies list JPanel", reg_consultancy_job);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_Registered_Consultancies_BtnActionPerformed

    private void Back_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_BtnActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_Back_BtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_Btn;
    private javax.swing.JButton New_Consultancies;
    private javax.swing.JButton Registered_Consultancies_Btn;
    // End of variables declaration//GEN-END:variables
}
