/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VeteranOrg.VeteranRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.VeteranOrganization.VeteranOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author mahaksingh
 */
public class SalaryCompanyGraphJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount account;
    private EcoSystem business;
    private VeteranOrganization organization;

    /**
     * Creates new form SalaryCompanyGraphJPanel
     */
    public SalaryCompanyGraphJPanel(JPanel userProcessContainer, UserAccount account,VeteranOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salaryCompanyJPanel = new javax.swing.JPanel();
        showChartBtn = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salaryCompanyJPanel.setBackground(new java.awt.Color(102, 102, 102));
        salaryCompanyJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        salaryCompanyJPanel.setLayout(new javax.swing.BoxLayout(salaryCompanyJPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(salaryCompanyJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 510));

        showChartBtn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        showChartBtn.setForeground(new java.awt.Color(0, 51, 255));
        showChartBtn.setText("Show Chart");
        showChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showChartBtnActionPerformed(evt);
            }
        });
        add(showChartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        Back.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        Back.setForeground(new java.awt.Color(0, 51, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void showChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showChartBtnActionPerformed
        // TODO add your handling code here:
         DefaultCategoryDataset dcd = new DefaultCategoryDataset();
        dcd.setValue(120000, "Salary", "ManTech International Corporation");
        dcd.setValue(78950, "Salary", "Intelligent Waves");
        dcd.setValue(98045, "Salary", "Delta");
        dcd.setValue(60976, "Salary", "Costco Wholesale");
        dcd.setValue(67852, "Salary", "USAA");
        dcd.setValue(58795, "Salary", "Northrop Grumman");
         dcd.setValue(86372, "Salary", "FBI");
          dcd.setValue(72986,"Salary", "Schneider National");
        
        JFreeChart jchart = ChartFactory.createBarChart("Company based on Salary", "Company", "Salary", dcd, PlotOrientation.VERTICAL, true, true, true);
        CategoryPlot cplot = jchart.getCategoryPlot();
        cplot.setRangeGridlinePaint(Color.black);
        ((BarRenderer) cplot.getRenderer()).setBarPainter(new StandardBarPainter());
        BarRenderer r = (BarRenderer) jchart.getCategoryPlot().getRenderer();
        r.setSeriesPaint(0, Color.red);

        
        ChartPanel chartPanel = new ChartPanel(jchart);

        salaryCompanyJPanel.removeAll();
        salaryCompanyJPanel.add(chartPanel);
        salaryCompanyJPanel.updateUI();
    }//GEN-LAST:event_showChartBtnActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel salaryCompanyJPanel;
    private javax.swing.JButton showChartBtn;
    // End of variables declaration//GEN-END:variables
}
