/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ConsultancyOrg.ConsultantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ConsultancyOrganization.ConsultantOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhargavisabbisetty
 */
public class ConsultantWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private EcoSystem business;
    UserAccount account;

    /**
     * Creates new form ConsultantWorkJPanel
     */
    public ConsultantWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ConsultantOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vvBTN = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Superclarendon", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Welcome! Consultancy!");

        vvBTN.setText("View New Request");
        vvBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vvBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(443, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(vvBTN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(vvBTN)
                .addContainerGap(348, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void vvBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vvBTNActionPerformed
        // TODO add your handling code here:
        ConsultantViewNewRequestWorkAreaJPanel vvJPanel = new ConsultantViewNewRequestWorkAreaJPanel(userProcessContainer, business,account);
        userProcessContainer.add("", vvJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_vvBTNActionPerformed

//
//    ConsultantViewNewRequestWorkAreaJPanel vvJPanel = new ConsultantViewNewRequestWorkAreaJPanel(userProcessContainer);
//        userProcessContainer.add("", vvJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
//    
//    ConsultantViewJobWorkAreaJPanel vjJPanel = new ConsultantViewJobWorkAreaJPanel(userProcessContainer);
//        userProcessContainer.add("manageOrganizationJPanel", vjJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton vvBTN;
    // End of variables declaration//GEN-END:variables
}
