/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.JobProviderOrg.JobPostingRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.JobDetails.JobDetails;
import Business.JobDetails.JobDetails.JobType;
import Business.Organization.JobProviderOrganization.JobPostingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobPostingWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author mahaksingh
 */
public class JobPostingJPanel extends javax.swing.JPanel {

    private Enterprise enterprise;
    private UserAccount userAccount;
    private JobPostingOrganization organization;
    private final JPanel userProcessContainer;
    private final EcoSystem business;

    /**
     * Creates new form JobPostingJPanel
     */
    public JobPostingJPanel(JPanel userProcessContainer, UserAccount account,JobPostingOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
        this.organization = organization;
        //valueLabel.setText(enterprise.getName());
        populateComboBox1();
        //populateRequestTable();
        
    }

    
public void populateComboBox1() {
        JobType_TB.removeAllItems();
        for (JobDetails.JobType jobDetails : JobDetails.JobType.values()) {
            JobType_TB.addItem(jobDetails);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Cmp_TB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        JobTitle_TB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JDesc_TB = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sal2_TB = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        JobType_TB = new javax.swing.JComboBox();
        backButton = new javax.swing.JButton();
        Location_CB = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Zapfino", 1, 18)); // NOI18N
        jLabel1.setText("Welvets");

        jLabel2.setFont(new java.awt.Font("Zapfino", 0, 14)); // NOI18N
        jLabel2.setText("for Employers");

        jLabel3.setFont(new java.awt.Font("Superclarendon", 1, 13)); // NOI18N
        jLabel3.setText("Job Details");

        jLabel4.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Company Name");

        jLabel5.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Job - Type");

        jLabel6.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Location of Job ");

        jLabel7.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Job Title");

        JobTitle_TB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JobTitle_TBActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Job Description");

        JDesc_TB.setColumns(20);
        JDesc_TB.setRows(5);
        jScrollPane1.setViewportView(JDesc_TB);

        jLabel9.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel9.setText("Optional Details");

        jLabel10.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        jLabel10.setText("Adding more details to your job description can increase your chances of attracting candidates.");

        jLabel15.setFont(new java.awt.Font("Superclarendon", 0, 8)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("($) USD per year");

        saveBtn.setBackground(new java.awt.Color(0, 51, 255));
        saveBtn.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        JobType_TB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        backButton.setBackground(new java.awt.Color(0, 51, 255));
        backButton.setFont(new java.awt.Font("Superclarendon", 0, 13)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        Location_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atlanta", "Austin", "Boston", "Charlotte", "Chicago", "Dallas", "Denver", "Detroit", "Houston", "Los Angeles", "Memphis", "New York", "Oklahoma  City", "Portland", "Raleigh", "San Antonio", "San Francisco", "San Jose", "Seattle", "Washington, D.C." }));
        Location_CB.setActionCommand("null");
        Location_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Location_CBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JobTitle_TB, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Cmp_TB, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JobType_TB, javax.swing.GroupLayout.Alignment.LEADING, 0, 249, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sal2_TB, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Location_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Cmp_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(JobType_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(JobTitle_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(24, 24, 24)
                .addComponent(Location_CB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sal2_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(backButton))
                .addContainerGap(250, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        JobDetails jobDetails = new JobDetails();
        jobDetails.setCompanyName(Cmp_TB.getText());
        jobDetails.setJobType((JobType)JobType_TB.getSelectedItem());
        jobDetails.setJobTitle(JobTitle_TB.getText());
        jobDetails.setLocation(Location_CB.getSelectedItem().toString());
       // jobDetails.setLocation(Jloc_TB.getText());
        jobDetails.setMaxSalary(Double.parseDouble((sal2_TB.getText())));
        //jobDetails.setMinSalary(Double.parseDouble((sal1_TB.getText())));
        jobDetails.setJobDescription(JDesc_TB.getText());
         
       
       JobPostingWorkRequest jobpostingWorkRequest = new JobPostingWorkRequest();
       jobpostingWorkRequest.setJobdetails(jobDetails);
       jobpostingWorkRequest.setSender(userAccount);
       jobpostingWorkRequest.setStatus("Posting Open");
      organization.getWorkQueue().getWorkRequestList().add(jobpostingWorkRequest);
       JOptionPane.showMessageDialog(null, "You have successfully created Job!!");
       //saveBtn.setEnabled(false);
        


    }//GEN-LAST:event_saveBtnActionPerformed

    private void JobTitle_TBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JobTitle_TBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JobTitle_TBActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageJobPostingJPanel mjpjp = (ManageJobPostingJPanel) component;
        mjpjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void Location_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Location_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Location_CBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cmp_TB;
    private javax.swing.JTextArea JDesc_TB;
    private javax.swing.JTextField JobTitle_TB;
    private javax.swing.JComboBox JobType_TB;
    private javax.swing.JComboBox Location_CB;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sal2_TB;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
